-- =====================================================================
-- 20 in 30 Project Tracker — Supabase schema
-- Run once in Supabase → SQL Editor → New query → paste → Run.
-- Safe to re-run.
-- =====================================================================

-- ---------- 1. Status options (edit these rows to change the choices) ----------
create table if not exists public.stage_statuses (
  name        text primary key,
  sort_order  int  not null default 100,
  -- category drives every calculation:
  --   'pending'  = not started
  --   'progress' = underway (counts as In Progress)
  --   'done'     = complete (earns the step's completion weight)
  category    text not null check (category in ('pending','progress','done'))
);

insert into public.stage_statuses (name, sort_order, category) values
  ('Pending',        10, 'pending'),
  ('In Progress',    20, 'progress'),
  ('Expected today', 30, 'progress'),
  ('Done',           90, 'done')
on conflict (name) do nothing;

-- ---------- 2. Videos: one row per film, same columns as the Excel sheet ----------
create table if not exists public.videos (
  id                   uuid primary key default gen_random_uuid(),
  sno                  integer generated by default as identity unique,  -- S.NO, automatic
  month                text,              -- 'YYYY-MM', e.g. '2026-09'
  product              text,
  usage                text,
  feature              text not null,     -- film / feature name
  durations            integer[] not null default '{}',  -- seconds: 15 / 20 / 30 / 40
  maker                text,
  agency               text,
  cost                 numeric(14,2),     -- ₹ amount
  cost_note            text,              -- e.g. 'TBC' when no amount yet
  digital_fpr          text,
  brand_checker        text,
  delivery_date        date,
  go_live_date         date,
  remarks              text,
  -- workflow steps ("Detailed status of films" columns)
  stage_agreement      text not null default 'Pending' references public.stage_statuses(name) on update cascade,
  stage_ai_addendum    text not null default 'Pending' references public.stage_statuses(name) on update cascade,
  stage_onboarding     text not null default 'Pending' references public.stage_statuses(name) on update cascade,
  stage_brand_script   text not null default 'Pending' references public.stage_statuses(name) on update cascade,
  stage_product_script text not null default 'Pending' references public.stage_statuses(name) on update cascade,
  stage_bco_script     text not null default 'Pending' references public.stage_statuses(name) on update cascade,
  stage_storyboarding  text not null default 'Pending' references public.stage_statuses(name) on update cascade,
  stage_legal          text not null default 'Pending' references public.stage_statuses(name) on update cascade,
  stage_first_cut      text not null default 'Pending' references public.stage_statuses(name) on update cascade,
  stage_final_cut      text not null default 'Pending' references public.stage_statuses(name) on update cascade,
  stage_go_live        text not null default 'Pending' references public.stage_statuses(name) on update cascade,
  updated_by           text,
  created_at           timestamptz not null default now(),
  updated_at           timestamptz not null default now()
);

create index if not exists videos_maker_idx   on public.videos (maker);
create index if not exists videos_product_idx on public.videos (product);

-- ---------- 3. Audit trail: one row per step status change ----------
create table if not exists public.status_history (
  id              bigint generated always as identity primary key,
  video_id        uuid not null references public.videos(id) on delete cascade,
  stage           text not null,          -- column name, e.g. 'stage_first_cut'
  previous_status text,                   -- null when the video was just created
  new_status      text not null,
  changed_by      text not null,
  changed_at      timestamptz not null default now(),
  comments        text
);
create index if not exists status_history_video_idx on public.status_history (video_id, changed_at desc);

-- ---------- 4. save_video(): the only way the app writes ----------
-- * Applies only the fields present in p_patch, so two people editing
--   different steps of the same video never overwrite each other.
-- * Stamps updated_by / updated_at.
-- * Writes a status_history row for every step that changed.
-- All in one transaction. Pass p_id = null to create a new video.
drop function if exists public.save_video(uuid, jsonb, text, text);
create function public.save_video(
  p_id uuid, p_patch jsonb, p_changed_by text, p_comment text default null
) returns public.videos
language plpgsql
security definer
set search_path = public
as $$
declare
  v_old   public.videos;
  v_new   public.videos;
  v_old_j jsonb;
  v_new_j jsonb;
  k       text;
  stage_cols text[] := array['stage_agreement','stage_ai_addendum','stage_onboarding',
    'stage_brand_script','stage_product_script','stage_bco_script','stage_storyboarding',
    'stage_legal','stage_first_cut','stage_final_cut','stage_go_live'];
begin
  if coalesce(btrim(p_changed_by), '') = '' then
    raise exception 'Please enter your name before saving.';
  end if;
  if p_patch is null or jsonb_typeof(p_patch) <> 'object' then
    raise exception 'Nothing to save.';
  end if;

  if p_id is null then
    if coalesce(btrim(p_patch->>'feature'), '') = '' then
      raise exception 'Feature (film name) is required.';
    end if;
    insert into public.videos (feature, updated_by)
    values (btrim(p_patch->>'feature'), btrim(p_changed_by))
    returning * into v_old;
    v_old_j := '{}'::jsonb;   -- so the starting statuses are logged
  else
    select * into v_old from public.videos where id = p_id for update;
    if not found then raise exception 'This video no longer exists.'; end if;
    v_old_j := to_jsonb(v_old);
  end if;

  update public.videos set
    month         = case when p_patch ? 'month'         then nullif(p_patch->>'month','')                 else month end,
    product       = case when p_patch ? 'product'       then nullif(btrim(p_patch->>'product'),'')       else product end,
    usage         = case when p_patch ? 'usage'         then nullif(btrim(p_patch->>'usage'),'')         else usage end,
    feature       = case when coalesce(btrim(p_patch->>'feature'),'') <> '' then btrim(p_patch->>'feature') else feature end,
    durations     = case when p_patch ? 'durations' then coalesce(
                      (select array_agg(x::int order by x::int) from jsonb_array_elements_text(p_patch->'durations') x),
                      '{}'::integer[])
                    else durations end,
    maker         = case when p_patch ? 'maker'         then nullif(btrim(p_patch->>'maker'),'')         else maker end,
    agency        = case when p_patch ? 'agency'        then nullif(btrim(p_patch->>'agency'),'')        else agency end,
    cost          = case when p_patch ? 'cost'          then nullif(p_patch->>'cost','')::numeric         else cost end,
    cost_note     = case when p_patch ? 'cost_note'     then nullif(btrim(p_patch->>'cost_note'),'')     else cost_note end,
    digital_fpr   = case when p_patch ? 'digital_fpr'   then nullif(btrim(p_patch->>'digital_fpr'),'')   else digital_fpr end,
    brand_checker = case when p_patch ? 'brand_checker' then nullif(btrim(p_patch->>'brand_checker'),'') else brand_checker end,
    delivery_date = case when p_patch ? 'delivery_date' then nullif(p_patch->>'delivery_date','')::date  else delivery_date end,
    go_live_date  = case when p_patch ? 'go_live_date'  then nullif(p_patch->>'go_live_date','')::date   else go_live_date end,
    remarks       = case when p_patch ? 'remarks'       then nullif(p_patch->>'remarks','')              else remarks end,
    stage_agreement      = coalesce(p_patch->>'stage_agreement',      stage_agreement),
    stage_ai_addendum    = coalesce(p_patch->>'stage_ai_addendum',    stage_ai_addendum),
    stage_onboarding     = coalesce(p_patch->>'stage_onboarding',     stage_onboarding),
    stage_brand_script   = coalesce(p_patch->>'stage_brand_script',   stage_brand_script),
    stage_product_script = coalesce(p_patch->>'stage_product_script', stage_product_script),
    stage_bco_script     = coalesce(p_patch->>'stage_bco_script',     stage_bco_script),
    stage_storyboarding  = coalesce(p_patch->>'stage_storyboarding',  stage_storyboarding),
    stage_legal          = coalesce(p_patch->>'stage_legal',          stage_legal),
    stage_first_cut      = coalesce(p_patch->>'stage_first_cut',      stage_first_cut),
    stage_final_cut      = coalesce(p_patch->>'stage_final_cut',      stage_final_cut),
    stage_go_live        = coalesce(p_patch->>'stage_go_live',        stage_go_live),
    updated_by    = btrim(p_changed_by),
    updated_at    = now()
  where id = v_old.id
  returning * into v_new;

  v_new_j := to_jsonb(v_new);
  foreach k in array stage_cols loop
    if (v_old_j->>k) is distinct from (v_new_j->>k)
       and not (p_id is null and v_new_j->>k = 'Pending') then
      insert into public.status_history (video_id, stage, previous_status, new_status, changed_by, comments)
      values (v_new.id, k, v_old_j->>k, v_new_j->>k, btrim(p_changed_by), nullif(btrim(coalesce(p_comment,'')),''));
    end if;
  end loop;

  return v_new;
end;
$$;

-- ---------- 5. Row Level Security ----------
-- Version 1: anyone with the link can READ; nobody writes to tables directly.
-- All writes go through save_video(), which validates the input.
alter table public.videos          enable row level security;
alter table public.status_history  enable row level security;
alter table public.stage_statuses  enable row level security;

drop policy if exists "read videos"   on public.videos;
drop policy if exists "read history"  on public.status_history;
drop policy if exists "read statuses" on public.stage_statuses;
create policy "read videos"   on public.videos         for select to anon, authenticated using (true);
create policy "read history"  on public.status_history for select to anon, authenticated using (true);
create policy "read statuses" on public.stage_statuses for select to anon, authenticated using (true);

revoke insert, update, delete on public.videos, public.status_history, public.stage_statuses from anon, authenticated;
grant select on public.videos, public.status_history, public.stage_statuses to anon, authenticated;

revoke all on function public.save_video(uuid, jsonb, text, text) from public;
grant execute on function public.save_video(uuid, jsonb, text, text) to anon, authenticated;

-- ---------- 6. Realtime (live dashboard) ----------
do $$ begin
  begin alter publication supabase_realtime add table public.videos;         exception when duplicate_object then null; end;
  begin alter publication supabase_realtime add table public.stage_statuses; exception when duplicate_object then null; end;
end $$;
