-- =====================================================================
-- Seed: the 31 films from the Excel sheet (Sep 2026).
-- Run AFTER schema.sql, once, in Supabase → SQL Editor.
-- Excel "Yes"/"Done" → Done, blank → Pending, "Expected today" kept as is.
-- =====================================================================
insert into public.videos (sno, month, product, usage, feature, durations, maker, agency, cost, cost_note, digital_fpr, brand_checker, delivery_date, go_live_date, remarks, stage_agreement, stage_ai_addendum, stage_onboarding, stage_brand_script, stage_product_script, stage_bco_script, stage_storyboarding, stage_legal, stage_first_cut, stage_brand_approval, stage_all_edits, stage_go_live, updated_by) values
  (1, '2026-09', 'CC', 'DPA', 'Rupay Convenience - AI', '{20,30}', 'Mayank', 'ASR', 385000, null, 'Rhea/Prachi', 'Varun', '2026-09-22', null, 'Delivered on 4th but error was realised later. Video getting revised. Ontrack for month end', 'Done', 'Done', 'Done', 'Done', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Excel import'),
  (2, '2026-09', 'CC', 'DPA', 'Rupay Convenience - Creator', '{20,30,40}', 'Kruthi', 'Dentsu AMP', 200000, null, 'Rhea/Prachi', 'Varun', '2026-09-22', null, 'delayed but ontrack', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Excel import'),
  (3, '2026-09', 'CC', 'DPA', 'Good Limits - AI', '{20,30}', 'Mayank', 'ASR', 385000, null, 'Rhea/Prachi', 'Varun', '2026-09-04', null, null, 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Done', 'Excel import'),
  (4, '2026-09', 'CC', 'DPA', 'Good Limits - Creator', '{20,30,40}', 'Kruthi', 'Dentsu AMP', 200000, null, 'Rhea/Prachi', 'Varun', '2026-09-22', null, 'delayed but ontrack', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Excel import'),
  (5, '2026-09', 'CC', 'Performance', 'Alumni Graduation - AI', '{15}', 'Rhea /Medhavi', 'ASR', 175000, null, 'Rhea/Prachi', 'Manan', '2026-09-28', null, 'Ontrack 1st cut received', 'Done', 'Done', 'Done', 'Done', 'Done', 'Done', 'Done', 'Pending', 'Pending', 'Pending', 'Pending', 'Excel import'),
  (6, '2026-09', 'CC', 'Performance', 'Alumni (BMS) Group Chat - AI', '{15}', 'Rhea /Medhavi', 'Film Baker', 60000, null, 'Rhea/Prachi', 'Manan', '2026-09-27', null, 'Ontrack 1st cut tomorrow 22/9', 'Done', 'Done', 'Pending', 'Done', 'Done', 'Done', 'Done', 'Pending', 'Pending', 'Pending', 'Pending', 'Excel import'),
  (7, '2026-09', 'CC', 'Performance', 'BAU (BMS) Talking Card - AI', '{15}', 'Akshat', 'Film Baker', 60000, null, 'Rhea/Prachi', 'Manan', '2026-09-28', null, 'Ontrack 1st cut tomorrow 22/9', 'Done', 'Done', 'Pending', 'Done', 'Done', 'Done', 'Done', 'Pending', 'Pending', 'Pending', 'Pending', 'Excel import'),
  (8, '2026-09', 'CC', 'Awareness', 'Festive Master - AI', '{30}', 'Mayank', 'Impulse', 250000, null, 'Rhea/Prachi', 'Pratik', '2026-09-26', null, 'Ontrack. Agreement pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Excel import'),
  (9, '2026-09', 'CC', 'Awareness', 'Festive - Mobile iPhone - AI', '{15}', 'Mayank', 'Impulse', 100000, null, 'Rhea/Prachi', 'Pratik', '2026-09-28', null, 'Ontrack. Agreement pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Excel import'),
  (10, '2026-09', 'CC', 'Awareness', 'Festive - Mobile Pixel - AI', '{15}', 'Mayank', 'Impulse', 100000, null, 'Rhea/Prachi', 'Pratik', '2026-09-28', null, 'Ontrack. Agreement pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Excel import'),
  (11, '2026-09', 'CC', 'Awareness', 'Festive - Electronics - AI', '{15}', 'Mayank', 'Impulse', 100000, null, 'Rhea/Prachi', 'Pratik', '2026-09-28', null, 'Ontrack. Agreement pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Excel import'),
  (12, '2026-09', 'CC', 'Awareness', 'Festive - Travel - AI', '{15}', 'Mayank', 'Impulse', 100000, null, 'Rhea/Prachi', 'Pratik', '2026-09-28', null, 'Ontrack. Agreement pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Excel import'),
  (13, '2026-09', 'CC', 'Performance', 'Rupay Convenience - AI', '{15}', 'Varun', 'Inhouse', 30000, null, 'Rhea/Prachi', 'Manan', '2026-09-11', null, null, 'Done', 'Done', 'Done', 'Done', 'Done', 'Done', 'Done', 'Pending', 'Pending', 'Done', 'Done', 'Excel import'),
  (14, '2026-09', 'Savings', 'DPA', 'Investments in iMobile - AI', '{20,30}', 'Kruthi', 'ASR', 400000, null, 'Aditya /Akshat', 'Varun', '2026-09-22', null, 'Ontrack. Slight delay but will be delivered', 'Done', 'Done', 'Done', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Excel import'),
  (15, '2026-09', 'Savings', 'DPA', 'Payments in iMobile- AI', '{20,30}', 'Kruthi', 'ASR', 400000, null, 'Aditya /Akshat', 'Varun', '2026-09-22', null, 'Ontrack. Slight delay but will be delivered', 'Done', 'Done', 'Done', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Excel import'),
  (16, '2026-09', 'Salary', 'DPA', 'Investments in iMobile - AI Repurposed', '{20,30}', 'Kruthi', 'ASR', 100000, null, 'Aditya /Akshat', 'Varun', '2026-09-22', null, 'Ontrack. Slight delay but will be delivered', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Excel import'),
  (17, '2026-09', 'Salary', 'DPA', 'Payments in iMobile- AI Repurposed', '{20,30}', 'Kruthi', 'ASR', 100000, null, 'Aditya /Akshat', 'Varun', '2026-09-22', null, 'Ontrack. Slight delay but will be delivered', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Excel import'),
  (18, '2026-09', 'Savings', 'DPA', 'Investments & Payments in iMobile - Creator', '{20,40}', 'Kruthi', 'Dentsu AMP', 200000, null, 'Aditya /Akshat', 'Varun', '2026-09-29', null, 'Ontrack', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Excel import'),
  (19, '2026-09', 'Salary', 'DPA', 'Investments & Payments in iMobile - Creator, Repurposed', '{20,40}', 'Kruthi', 'Dentsu AMP', 100000, null, 'Aditya /Akshat', 'Varun', '2026-09-29', null, 'Ontrack', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Excel import'),
  (20, '2026-09', 'Savings', 'Performance', 'SmartLock on iMobile - AI - Nilesh', '{15}', 'Akshat', 'Film Baker', 60000, null, 'Aditya /Akshat', 'Manan', '2026-09-28', null, 'Ontrack 1st cut tomorrow 22/9', 'Done', 'Done', 'Pending', 'Done', 'Done', 'Done', 'Done', 'Pending', 'Pending', 'Pending', 'Pending', 'Excel import'),
  (21, '2026-09', 'Salary', 'Performance', 'All investments, payments in one place - AI', '{15}', 'Akshat', 'Film Baker', 60000, null, 'Aditya /Akshat', 'Manan', '2026-09-28', null, 'Ontrack Delayed but finishing by 30 sep', 'Done', 'Done', 'Pending', 'Done', 'Done', 'Done', 'Done', 'Pending', 'Pending', 'Pending', 'Pending', 'Excel import'),
  (22, '2026-09', 'Savings', 'Performance', 'UPI, Bill payments, Loans, Investments in iMobile - AI', '{20}', 'Akshat', 'ASR', 175000, null, 'Aditya /Akshat', 'Manan', '2026-09-28', null, 'Ontrack 1st cut tomorrow 22/9', 'Done', 'Done', 'Pending', 'Done', 'Done', 'Done', 'Done', 'Pending', 'Pending', 'Pending', 'Pending', 'Excel import'),
  (23, '2026-09', 'Savings', 'Performance', 'Branch + ATM + Phone Banking Network - AI', '{15}', 'Manan', 'Inhouse', 30000, null, 'Aditya /Akshat', 'Varun', '2026-09-17', null, 'Ontrack. Product & BCO approvals pending.', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Excel import'),
  (24, '2026-09', 'Multiasset', 'Performance', 'AL - Loan up to 100% of on-road price PL - Loan up to Rs. 50 L - AI', '{20}', 'Aradhita', 'Inhouse', 30000, null, 'Harsh', 'Sulbha', '2026-09-18', null, 'Delivery done. Go live pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Excel import'),
  (25, '2026-09', 'Multiasset', 'Performance', 'AL - EMIs starting Rs. 1572/lakh* PL - Interest rate starting from 9.99% - AI', '{20}', 'Harsh', 'Inhouse', 30000, null, 'Harsh', 'Sulbha', '2026-09-30', null, 'Ontrack. This is delayed beyond 5 days. Work handed over to Priya', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Excel import'),
  (26, '2026-09', 'Personal Loan', 'Performance', 'Loan up to Rs. 50 L, Interest rate starting from 9.99% - AI', '{20}', 'Devaprabha', 'Inhouse', 30000, null, 'Priya', 'Sulbha', '2026-09-24', null, 'Ontrack. Delayed due to change in proposition', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Excel import'),
  (27, '2026-09', 'Personal Loan', 'Performance', 'Interest rate starting from 9.99%, Tenure up to 74 months - AI', '{20}', 'Priya', 'Inhouse', 30000, null, 'Priya', 'Sulbha', '2026-09-19', null, 'Ontrack. Approvals pending. Ongoing', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Excel import'),
  (28, '2026-09', 'Home Loan', 'Performance', 'Online sanction, minimal documentation - AI', '{20}', 'Anuja', 'Inhouse', 30000, null, 'Anuja', 'Sulbha', '2026-09-26', null, 'Ontrack', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Excel import'),
  (29, '2026-09', 'Home Loan', 'Performance', 'Attractive interest rate, minimal documentation - AI', '{20}', 'Lipika', 'Inhouse', 30000, null, 'Anuja', 'Sulbha', '2026-09-22', null, 'Delivery done. Go live pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Excel import'),
  (30, '2026-09', 'Current Account', 'Performance', 'Ease of Business Banking - AI', '{20}', 'Kajal', 'Persian Blue', null, 'TBC', 'Kajal', 'Kruthi', '2026-09-30', null, 'Ontrack', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Excel import'),
  (31, '2026-09', 'Current Account', 'Performance', '360 Business Banking - AI', '{20}', 'Kajal', 'Persian Blue', null, 'TBC', 'Kajal', 'Kruthi', '2026-09-30', null, 'Ontrack', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Pending', 'Excel import')
on conflict (sno) do nothing;

-- make the next new video get S.NO 32 (max + 1)
select setval(pg_get_serial_sequence('public.videos','sno'), (select coalesce(max(sno),0) from public.videos));
